Determine the live system from the original disk

diff --git a/pabrik-cc/extract-image b/pabrik-cc/extract-image
--- a/pabrik-cc/extract-image
+++ b/pabrik-cc/extract-image
@@ -22,8 +22,18 @@ mount -o loop $DISK_ORIGINAL $TMP/$DISK_MOUNTED
 echo "Copying the image's content"
 cp -a $TMP/$DISK_MOUNTED $DISK
 
+if [ -d $TMP/$DISK_MOUNTED/live ];then
+    LIVE_SYSTEM=live
+elif [ -d $TMP/$DISK_MOUNTED/casper ];then
+    LIVE_SYSTEM=casper
+else
+    echo "LIVE system can't be determined"
+    exit 1
+fi
+check_variable LIVE_SYSTEM
+
 # Mount the rootfs
-mount -o loop $TMP/$DISK_MOUNTED/live/filesystem.squashfs $TMP/$ROOTFS_MOUNTED
+mount -o loop $TMP/$DISK_MOUNTED/$LIVE_SYSTEM/filesystem.squashfs $TMP/$ROOTFS_MOUNTED
 
 # Copy the rootfs's content
 echo "Extracting image's content"
