Changes: Log time and memory spent

diff --git a/build-image b/build-image
--- a/build-image
+++ b/build-image
@@ -43,5 +43,15 @@ if [ -z "$CONFIG" -o -z "$DISK_ID" -o -z "$TMP" ];then
     exit 1
 fi
 
+LOG_FILE=$TMP/$DISK_ID-publish/log.txt
 mkdir -p $TMP/$DISK_ID-publish
-$CC_DIR/build-iso 2>&1 | tee $TMP/$DISK_ID-publish/log.txt
+set +e
+export TIME="Time spent: %E. Memory used: %K"
+/usr/bin/time $CC_DIR/build-iso >$LOG_FILE 2>&1
+
+if [ $? -eq 0 ];then
+    echo "Success."
+else
+    echo "Failed."
+fi
+set -e
